---

- apt:
    name: software-properties-common
    state: present
    update_cache: yes

- apt_repository:
    repo: 'ppa:certbot/certbot'

- name: install certbot
  apt:
    name: certbot
    state: present
    update_cache: yes
